In [5]:
import pandas as pd

data = pd.read_csv("E:\Youtube_Courses\Complete_Pandas_Course\Datasets_Files\student_data.csv")

df = pd.DataFrame(data)

df

     id    name   age        city  marks
0     1     Ali  20.0      Lahore   78.0
1     2   Ahmed  21.0     Karachi   85.0
2     3    Sara  19.0   Islamabad   90.0
3     4  Ayesha  22.0  Rawalpindi    NaN
4     5   Usman  20.0  Faisalabad   67.0
..  ...     ...   ...         ...    ...
95   96    Hina  21.0      Lahore   91.0
96   97   Bilal  23.0     Karachi   78.0
97   98  Zainab  20.0   Islamabad   85.0
98   99  Hassan  22.0  Rawalpindi   74.0
99  100   Maria  19.0  Faisalabad  100.0

[100 rows x 5 columns]

In [6]:
df["name"]

0        Ali
1      Ahmed
2       Sara
3     Ayesha
4      Usman
       ...
95      Hina
96     Bilal
97    Zainab
98    Hassan
99     Maria
Name: name, Length: 100, dtype: str

In [7]:
df[["name", "age"]]

      name   age
0      Ali  20.0
1    Ahmed  21.0
2     Sara  19.0
3   Ayesha  22.0
4    Usman  20.0
..     ...   ...
95    Hina  21.0
96   Bilal  23.0
97  Zainab  20.0
98  Hassan  22.0
99   Maria  19.0

[100 rows x 2 columns]

In [8]:
df.loc[0]

id            1
name        Ali
age        20.0
city     Lahore
marks      78.0
Name: 0, dtype: object

In [10]:
df.loc[0:3, ["name", "age"]]

     name   age
0     Ali  20.0
1   Ahmed  21.0
2    Sara  19.0
3  Ayesha  22.0

In [14]:
df.iloc[0]

id            1
name        Ali
age        20.0
city     Lahore
marks      78.0
Name: 0, dtype: object

In [15]:
df.iloc[0:3]

   id   name   age       city  marks
0   1    Ali  20.0     Lahore   78.0
1   2  Ahmed  21.0    Karachi   85.0
2   3   Sara  19.0  Islamabad   90.0

In [17]:
df.iloc[0:3, 0:3]

   id   name   age
0   1    Ali  20.0
1   2  Ahmed  21.0
2   3   Sara  19.0

In [26]:
df[(df["age"] > 21) & (df["marks"] > 70)]

    id    name   age        city  marks
6    7   Bilal  23.0     Karachi   74.0
13  14  Ayesha  22.0  Rawalpindi   77.0
23  24  Ayesha  22.0  Rawalpindi   80.0
26  27   Bilal  23.0     Karachi   76.0
28  29  Hassan  22.0         NaN   71.0
33  34  Ayesha  22.0  Rawalpindi   78.0
36  37   Bilal  23.0     Karachi   77.0
38  39  Hassan  22.0  Rawalpindi   73.0
43  44  Ayesha  22.0         NaN   82.0
46  47   Bilal  23.0     Karachi   78.0
48  49  Hassan  22.0  Rawalpindi   72.0
53  54  Ayesha  22.0  Rawalpindi   79.0
56  57   Bilal  23.0     Karachi   75.0
63  64  Ayesha  22.0  Rawalpindi   83.0
66  67   Bilal  23.0     Karachi   76.0
68  69  Hassan  22.0  Rawalpindi   71.0
73  74  Ayesha  22.0  Rawalpindi   80.0
78  79  Hassan  22.0  Rawalpindi   73.0
83  84  Ayesha  22.0  Rawalpindi   81.0
86  87   Bilal  23.0     Karachi   77.0
88  89  Hassan  22.0         NaN   72.0
96  97   Bilal  23.0     Karachi   78.0
98  99  Hassan  22.0  Rawalpindi   74.0

In [27]:
df[(df["age"] > 21) | (df["marks"] > 70)]

     id    name   age        city  marks
0     1     Ali  20.0      Lahore   78.0
1     2   Ahmed  21.0     Karachi   85.0
2     3    Sara  19.0   Islamabad   90.0
3     4  Ayesha  22.0  Rawalpindi    NaN
5     6    Hina   NaN      Lahore   92.0
..  ...     ...   ...         ...    ...
95   96    Hina  21.0      Lahore   91.0
96   97   Bilal  23.0     Karachi   78.0
97   98  Zainab  20.0   Islamabad   85.0
98   99  Hassan  22.0  Rawalpindi   74.0
99  100   Maria  19.0  Faisalabad  100.0

[86 rows x 5 columns]

In [32]:
df[df["age"].isin([10])]

Empty DataFrame
Columns: [id, name, age, city, marks]
Index: []

In [35]:
df.sort_values("name", ascending=False)

    id    name   age       city  marks
47  48  Zainab  20.0  Islamabad    NaN
77  78  Zainab  20.0  Islamabad   84.0
27  28  Zainab  20.0  Islamabad   82.0
67  68  Zainab  20.0  Islamabad   82.0
7    8  Zainab  20.0        NaN   81.0
..  ..     ...   ...        ...    ...
51  52   Ahmed  21.0    Karachi   83.0
61  62   Ahmed  21.0    Karachi   89.0
71  72   Ahmed  21.0    Karachi   85.0
91  92   Ahmed  21.0    Karachi   87.0
12  13     NaN  19.0  Islamabad   91.0

[100 rows x 5 columns]

In [36]:
df.reset_index(drop=True)

     id    name   age        city  marks
0     1     Ali  20.0      Lahore   78.0
1     2   Ahmed  21.0     Karachi   85.0
2     3    Sara  19.0   Islamabad   90.0
3     4  Ayesha  22.0  Rawalpindi    NaN
4     5   Usman  20.0  Faisalabad   67.0
..  ...     ...   ...         ...    ...
95   96    Hina  21.0      Lahore   91.0
96   97   Bilal  23.0     Karachi   78.0
97   98  Zainab  20.0   Islamabad   85.0
98   99  Hassan  22.0  Rawalpindi   74.0
99  100   Maria  19.0  Faisalabad  100.0

[100 rows x 5 columns]