In [1]:
import pandas as pd

In [3]:
numbers = [10, 20, 30, 40, 50]
series = pd.Series(numbers)

series

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [6]:
data = {
    "Name": ["Ali", "Sara", "Ahmed", "Hammad", "Kaif", "Rehan", "Ishfaq"],
    "Age": [22, 21, 23, 35, 26, 27, 28],
    "Marks": [85, 90, 88, 78, 69, 89, 67]
}

df = pd.DataFrame(data)

df

     Name  Age  Marks
0     Ali   22     85
1    Sara   21     90
2   Ahmed   23     88
3  Hammad   35     78
4    Kaif   26     69
5   Rehan   27     89
6  Ishfaq   28     67

In [7]:
df.head()

     Name  Age  Marks
0     Ali   22     85
1    Sara   21     90
2   Ahmed   23     88
3  Hammad   35     78
4    Kaif   26     69

In [8]:
df.tail()

     Name  Age  Marks
2   Ahmed   23     88
3  Hammad   35     78
4    Kaif   26     69
5   Rehan   27     89
6  Ishfaq   28     67

In [9]:
df.shape

(7, 3)

In [10]:
df.columns

Index(['Name', 'Age', 'Marks'], dtype='str')

In [11]:
df["Name"]

0       Ali
1      Sara
2     Ahmed
3    Hammad
4      Kaif
5     Rehan
6    Ishfaq
Name: Name, dtype: str

In [12]:
df[["Name", "Age"]]

     Name  Age
0     Ali   22
1    Sara   21
2   Ahmed   23
3  Hammad   35
4    Kaif   26
5   Rehan   27
6  Ishfaq   28

In [13]:
df.describe()

             Age      Marks
count   7.000000   7.000000
mean   26.000000  80.857143
std     4.760952   9.651055
min    21.000000  67.000000
25%    22.500000  73.500000
50%    26.000000  85.000000
75%    27.500000  88.500000
max    35.000000  90.000000