In [3]:
import pandas as pd

data = pd.read_csv("E:\Youtube_Courses\Complete_Pandas_Course\Datasets_Files\emp_data.csv")

df = pd.DataFrame(data)

df

      Name Department  Gender  Salary  Age
0      Ali         IT    Male   60000   25
1     Sara         HR  Female   50000   28
2    Ahmed    Finance    Male   70000   35
3   Ayesha         IT  Female   65000   30
4    Bilal         HR    Male   48000   26
..     ...        ...     ...     ...  ...
85   Zara5         HR  Female   59000   33
86  Usman5    Finance    Male   72000   36
87   Hina5         IT  Female   68000   32
88  Hamza5         HR    Male   48000   25
89   Noor5    Finance  Female   79000   43

[90 rows x 5 columns]

In [7]:
df.groupby(["Department", "Gender"])["Salary"].mean()

Department  Gender
Finance     Female    75200.000000
            Male      71066.666667
HR          Female    54333.333333
            Male      47866.666667
IT          Female    66200.000000
            Male      61866.666667
Name: Salary, dtype: float64

In [8]:
df.groupby("Department")["Salary"].agg(["mean", "max", "min"])

                    mean    max    min
Department
Finance     73133.333333  79000  68000
HR          51100.000000  59000  46000
IT          64033.333333  69000  60000

In [10]:
df.groupby("Department").agg({
    "Salary": "mean",
    "Age": "min"
})

                  Salary  Age
Department
Finance     73133.333333   32
HR          51100.000000   24
IT          64033.333333   25

In [11]:
df.groupby("Department")["Salary"].mean().reset_index()

  Department        Salary
0    Finance  73133.333333
1         HR  51100.000000
2         IT  64033.333333

In [13]:
df.groupby("Department")["Salary"].mean().sort_values(ascending=True)

Department
HR         51100.000000
IT         64033.333333
Finance    73133.333333
Name: Salary, dtype: float64

In [14]:
df.groupby("Department").count()

            Name  Gender  Salary  Age
Department
Finance       30      30      30   30
HR            30      30      30   30
IT            30      30      30   30

In [15]:
df.groupby("Department")["Name"].count()

Department
Finance    30
HR         30
IT         30
Name: Name, dtype: int64