In [1]:
import pandas as pd

In [2]:
df1 = pd.DataFrame({
    "ID": [1, 2, 3],
    "Name": ["Ali", "Sara", "Ahmed"]
})


df2 = pd.DataFrame({
    "ID": [1, 2, 3],
    "Marks": [85, 90, 88]
})

In [4]:
df2

   ID  Marks
0   1     85
1   2     90
2   3     88

In [5]:
merged_df = pd.merge(df1, df2, on="ID")

In [6]:
merged_df

   ID   Name  Marks
0   1    Ali     85
1   2   Sara     90
2   3  Ahmed     88

In [11]:
df3 = pd.DataFrame({
    "ID": [1, 2, 3],
    "Name": ["Ali", "Sara", "Ahmed"]
})


df4 = pd.DataFrame({
    "ID": [1, 4, 3],
    "Marks": [85, 90, 88]
})

inner_merged_df = pd.merge(df3, df4, on="ID", how="outer")

inner_merged_df

   ID   Name  Marks
0   1    Ali   85.0
1   2   Sara    NaN
2   3  Ahmed   88.0
3   4    NaN   90.0

In [13]:
df5 = pd.DataFrame({
    "StudentID": [1, 2, 3],
    "Name": ["Ali", "Sara", "Ahmed"]
})


df6 = pd.DataFrame({
    "ID": [1, 2, 3],
    "Marks": [85, 90, 88]
})

result = pd.merge(df5, df6, left_on="StudentID", right_on="ID")

result

   StudentID   Name  ID  Marks
0          1    Ali   1     85
1          2   Sara   2     90
2          3  Ahmed   3     88

In [16]:
df1 = pd.DataFrame({
    "Name": ["Ali", "Sara", "Ahmed"]
}, index=[1,2,3])


df2 = pd.DataFrame({
    "Marks": [85, 90, 88]
}, index=[1,2,3])

result = df1.join(df2)
result

    Name  Marks
1    Ali     85
2   Sara     90
3  Ahmed     88

In [23]:
df3 = pd.DataFrame({
    "ID": [1, 2, 3],
    "Name": ["Ali", "Sara", "Ahmed"]
})


df4 = pd.DataFrame({
    "ID": [1, 4, 3],
    "Marks": [85, 90, 88]
})

df3_index = df3.set_index("ID")
df4_index = df4.set_index("ID")

df3_index.join(df4_index, how="right")

     Name  Marks
ID
1     Ali     85
4     NaN     90
3   Ahmed     88

In [27]:
df1 = pd.DataFrame({
    "ID": [1, 2, 3],
    "Name": ["Ali", "Sara", "Ahmed"]
})


df2 = pd.DataFrame({
    "ID": [1, 2, 3],
    "Marks": [85, 90, 88]
})

pd.concat([df1, df2],  ignore_index=True)

   ID   Name  Marks
0   1    Ali    NaN
1   2   Sara    NaN
2   3  Ahmed    NaN
3   1    NaN   85.0
4   2    NaN   90.0
5   3    NaN   88.0