In [31]:
import pandas as pd 

data1 = pd.read_csv("E:\Youtube_Courses\Complete_Pandas_Course\Datasets_Files\missing_values.csv")

df1 = pd.DataFrame(data1)

df1

   ID    Name   Age  Marks
0   1     Ali  20.0   85.0
1   2    Sara   NaN   90.0
2   3   Usman  21.0    NaN
3   4  Ayesha  22.0   88.0
4   5   Hamza   NaN   76.0
5   6  Zainab  23.0   92.0
6   7   Bilal  20.0    NaN
7   8  Maryam   NaN   81.0
8   9   Ahmed  22.0   79.0
9  10    Noor  21.0   95.0

In [32]:
df1.isnull().sum()

ID       0
Name     0
Age      3
Marks    2
dtype: int64

In [37]:
acc_df1 = df1.dropna(axis=1)

acc_df1

acc_df1.shape

(10, 2)

In [ ]:
df1["Age"].fillna(20)
df1["Marks"].fillna(80)

0    85.0
1    90.0
2    80.0
3    88.0
4    76.0
5    92.0
6    80.0
7    81.0
8    79.0
9    95.0
Name: Marks, dtype: float64

In [43]:
df1

   ID    Name   Age  Marks
0   1     Ali  20.0   85.0
1   2    Sara   NaN   90.0
2   3   Usman  21.0    NaN
3   4  Ayesha  22.0   88.0
4   5   Hamza   NaN   76.0
5   6  Zainab  23.0   92.0
6   7   Bilal  20.0    NaN
7   8  Maryam   NaN   81.0
8   9   Ahmed  22.0   79.0
9  10    Noor  21.0   95.0

In [45]:
df1["Age"] = df1["Age"].fillna(df1["Age"].mean())

df1

   ID    Name        Age  Marks
0   1     Ali  20.000000   85.0
1   2    Sara  21.285714   90.0
2   3   Usman  21.000000    NaN
3   4  Ayesha  22.000000   88.0
4   5   Hamza  21.285714   76.0
5   6  Zainab  23.000000   92.0
6   7   Bilal  20.000000    NaN
7   8  Maryam  21.285714   81.0
8   9   Ahmed  22.000000   79.0
9  10    Noor  21.000000   95.0

In [46]:
data2 = pd.read_csv("E:\Youtube_Courses\Complete_Pandas_Course\Datasets_Files\duplicates.csv")

df2 = pd.DataFrame(data2)

df2

   ID    Name        City
0   1     Ali   Islamabad
1   2    Sara      Lahore
2   3   Usman     Karachi
3   4  Ayesha    Peshawar
4   5   Hamza  Rawalpindi
5   2    Sara      Lahore
6   4  Ayesha    Peshawar
7   6  Zainab      Multan
8   7   Bilal  Faisalabad
9   3   Usman     Karachi

In [47]:
df2.duplicated().sum()

np.int64(3)

In [48]:
df2.drop_duplicates()

   ID    Name        City
0   1     Ali   Islamabad
1   2    Sara      Lahore
2   3   Usman     Karachi
3   4  Ayesha    Peshawar
4   5   Hamza  Rawalpindi
7   6  Zainab      Multan
8   7   Bilal  Faisalabad

In [49]:
data3 = pd.read_csv("E:\Youtube_Courses\Complete_Pandas_Course\Datasets_Files\\rename_columns.csv")

df3 = pd.DataFrame(data3)

df3

   std_id std_name  std_marks    std_city
0       1      Ali         85   Islamabad
1       2     Sara         91      Lahore
2       3    Usman         78     Karachi
3       4   Ayesha         88    Peshawar
4       5    Hamza         76  Rawalpindi
5       6   Zainab         92      Multan
6       7    Bilal         81  Faisalabad
7       8   Maryam         87     Sialkot
8       9    Ahmed         79  Gujranwala
9      10     Noor         95      Quetta

In [51]:
df3.rename(columns={"std_name" : "Student_Name"}, inplace=True)

df3

   std_id Student_Name  std_marks    std_city
0       1          Ali         85   Islamabad
1       2         Sara         91      Lahore
2       3        Usman         78     Karachi
3       4       Ayesha         88    Peshawar
4       5        Hamza         76  Rawalpindi
5       6       Zainab         92      Multan
6       7        Bilal         81  Faisalabad
7       8       Maryam         87     Sialkot
8       9        Ahmed         79  Gujranwala
9      10         Noor         95      Quetta

In [52]:
data4 = pd.read_csv("E:\Youtube_Courses\Complete_Pandas_Course\Datasets_Files\string_cleaning.csv")

df4 = pd.DataFrame(data4)

df4

   ID           Name         City
0   1      Ali Khan           isl
1   2     SARA AHMED       lahore
2   3   usman tariq      Karachi
3   4    Ayesha Noor          isl
4   5     HAMZA ALI      peshawar
5   6   Zainab Malik   rawalpindi
6   7    bilal khan        Lahore
7   8   MARYAM IQBAL      karachi
8   9    Ahmed Raza           isl
9  10    NOOR FATIMA   faisalabad

In [55]:
df4["Name"] = df4["Name"].str.upper()

df4

   ID           Name         City
0   1      ALI KHAN           isl
1   2     SARA AHMED       lahore
2   3   USMAN TARIQ      Karachi
3   4    AYESHA NOOR          isl
4   5     HAMZA ALI      peshawar
5   6   ZAINAB MALIK   rawalpindi
6   7    BILAL KHAN        Lahore
7   8   MARYAM IQBAL      karachi
8   9    AHMED RAZA           isl
9  10    NOOR FATIMA   faisalabad

In [57]:
df4["City"] = df4["City"].str.replace("isl", "Islamabad")

df4

   ID           Name         City
0   1      ALI KHAN     Islamabad
1   2     SARA AHMED       lahore
2   3   USMAN TARIQ      Karachi
3   4    AYESHA NOOR    Islamabad
4   5     HAMZA ALI      peshawar
5   6   ZAINAB MALIK   rawalpindi
6   7    BILAL KHAN        Lahore
7   8   MARYAM IQBAL      karachi
8   9    AHMED RAZA     Islamabad
9  10    NOOR FATIMA   faisalabad

In [58]:
data5 = pd.read_csv("E:\Youtube_Courses\Complete_Pandas_Course\Datasets_Files\datatype.csv")

df5 = pd.DataFrame(data5)

df5

     Name  Age  Marks
0     Ali   21   85.5
1    Sara   22   90.0
2   Ahmed   20   78.5
3  Ayesha   23   88.0
4   Usman   24   92.5
5  Fatima   21   80.0
6   Bilal   22   75.5
7  Zainab   25   89.0
8  Hassan   26   95.0
9    Noor   20   82.5

In [59]:
df5.dtypes

Name         str
Age        int64
Marks    float64
dtype: object

In [64]:
df5["Age"] = df5["Age"].astype(int)

df5

     Name  Age  Marks
0     Ali   21   85.5
1    Sara   22   90.0
2   Ahmed   20   78.5
3  Ayesha   23   88.0
4   Usman   24   92.5
5  Fatima   21   80.0
6   Bilal   22   75.5
7  Zainab   25   89.0
8  Hassan   26   95.0
9    Noor   20   82.5

In [66]:
data6 = pd.read_csv("E:\Youtube_Courses\Complete_Pandas_Course\Datasets_Files\dates.csv")

df6 = pd.DataFrame(data6)

df6.dtypes

Event    str
Date     str
dtype: object

In [73]:
df6["Date"] = pd.to_datetime(df6["Date"])

df6["Year"] = df6["Date"].dt.year
df6["Day"] = df6["Date"].dt.day

df6

        Event       Date  Year  Day
0        Exam 2026-01-01  2026    1
1     Meeting 2026-02-15  2026   15
2     Holiday 2026-03-10  2026   10
3    Workshop 2026-04-05  2026    5
4     Seminar 2026-05-20  2026   20
5  Conference 2026-06-18  2026   18
6    Training 2026-07-22  2026   22
7        Test 2026-08-30  2026   30
8      Result 2026-09-12  2026   12
9   Admission 2026-10-25  2026   25

In [74]:
data7 = pd.read_csv("E:\Youtube_Courses\Complete_Pandas_Course\Datasets_Files\grades.csv")

df7 = pd.DataFrame(data7)

df7

  Student  Marks
0     Ali     95
1    Sara     82
2   Ahmed     76
3  Ayesha     89
4   Usman     91
5  Fatima     67
6   Bilal     88
7  Zainab     79
8  Hassan     84
9    Noor     90

In [75]:
def grade(marks):
    if marks >= 90:
        return "A"
    elif marks >= 80:
        return "B"
    else:
        return "C"
    
df7["Grade"] = df7["Marks"].apply(grade)

df7

  Student  Marks Grade
0     Ali     95     A
1    Sara     82     B
2   Ahmed     76     C
3  Ayesha     89     B
4   Usman     91     A
5  Fatima     67     C
6   Bilal     88     B
7  Zainab     79     C
8  Hassan     84     B
9    Noor     90     A

In [76]:
data8 = pd.read_csv("E:\Youtube_Courses\Complete_Pandas_Course\Datasets_Files\\new_columns.csv")

df8 = pd.DataFrame(data8)

df8

  Student  Marks1  Marks2
0     Ali      80      85
1    Sara      75      80
2   Ahmed      90      88
3  Ayesha      85      90
4   Usman      88      92
5  Fatima      70      75
6   Bilal      95      96
7  Zainab      78      81
8  Hassan      82      84
9    Noor      89      91

In [77]:
df8["Total_Marks"] = df8["Marks1"] + df8["Marks2"]

df8

  Student  Marks1  Marks2  Total_Marks
0     Ali      80      85          165
1    Sara      75      80          155
2   Ahmed      90      88          178
3  Ayesha      85      90          175
4   Usman      88      92          180
5  Fatima      70      75          145
6   Bilal      95      96          191
7  Zainab      78      81          159
8  Hassan      82      84          166
9    Noor      89      91          180