In [2]:
import pandas as pd

df = pd.read_csv("Datasets_Files/student_data.csv")

df

     id    name   age        city  marks
0     1     Ali  20.0      Lahore   78.0
1     2   Ahmed  21.0     Karachi   85.0
2     3    Sara  19.0   Islamabad   90.0
3     4  Ayesha  22.0  Rawalpindi    NaN
4     5   Usman  20.0  Faisalabad   67.0
..  ...     ...   ...         ...    ...
95   96    Hina  21.0      Lahore   91.0
96   97   Bilal  23.0     Karachi   78.0
97   98  Zainab  20.0   Islamabad   85.0
98   99  Hassan  22.0  Rawalpindi   74.0
99  100   Maria  19.0  Faisalabad  100.0

[100 rows x 5 columns]

In [4]:
df2 = pd.read_excel("Datasets_Files/student_data.xlsx")

df2

     id    name   age        city  marks
0     1    Sara  23.0   Islamabad   99.0
1     2  Ayesha  22.0  Faisalabad   61.0
2     3    Hina  20.0  Rawalpindi   98.0
3     4  Hassan  21.0      Lahore   98.0
4     5    Hina  23.0  Rawalpindi   88.0
..  ...     ...   ...         ...    ...
95   96   Usman  18.0     Karachi   91.0
96   97    Hina  21.0  Faisalabad   85.0
97   98   Bilal  18.0  Faisalabad    NaN
98   99   Bilal  20.0      Lahore   78.0
99  100     Ali  19.0   Islamabad   72.0

[100 rows x 5 columns]

In [5]:
df.head()

   id    name   age        city  marks
0   1     Ali  20.0      Lahore   78.0
1   2   Ahmed  21.0     Karachi   85.0
2   3    Sara  19.0   Islamabad   90.0
3   4  Ayesha  22.0  Rawalpindi    NaN
4   5   Usman  20.0  Faisalabad   67.0

In [6]:
df.tail()

     id    name   age        city  marks
95   96    Hina  21.0      Lahore   91.0
96   97   Bilal  23.0     Karachi   78.0
97   98  Zainab  20.0   Islamabad   85.0
98   99  Hassan  22.0  Rawalpindi   74.0
99  100   Maria  19.0  Faisalabad  100.0

In [7]:
df.head(10)

   id    name   age        city  marks
0   1     Ali  20.0      Lahore   78.0
1   2   Ahmed  21.0     Karachi   85.0
2   3    Sara  19.0   Islamabad   90.0
3   4  Ayesha  22.0  Rawalpindi    NaN
4   5   Usman  20.0  Faisalabad   67.0
5   6    Hina   NaN      Lahore   92.0
6   7   Bilal  23.0     Karachi   74.0
7   8  Zainab  20.0         NaN   81.0
8   9  Hassan  22.0  Rawalpindi   69.0
9  10   Maria  19.0  Faisalabad   95.0

In [8]:
df.shape

(100, 5)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      100 non-null    int64
 1   name    99 non-null     str
 2   age     95 non-null     float64
 3   city    94 non-null     str
 4   marks   92 non-null     float64
dtypes: float64(2), int64(1), str(2)
memory usage: 4.0 KB

In [10]:
df.dtypes

id         int64
name         str
age      float64
city         str
marks    float64
dtype: object

In [11]:
df.isnull().sum()

id       0
name     1
age      5
city     6
marks    8
dtype: int64

In [14]:
df_accurate = df.dropna()

df_accurate.info()

<class 'pandas.DataFrame'>
Index: 80 entries, 0 to 99
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      80 non-null     int64
 1   name    80 non-null     str
 2   age     80 non-null     float64
 3   city    80 non-null     str
 4   marks   80 non-null     float64
dtypes: float64(2), int64(1), str(2)
memory usage: 3.8 KB

In [16]:
df_accurate.describe()

               id       age      marks
count   80.000000  80.00000   80.00000
mean    53.112500  20.65000   82.10000
std     28.739332   1.26391    9.51428
min      1.000000  19.00000   65.00000
25%     29.500000  20.00000   75.75000
50%     53.500000  20.00000   81.50000
75%     78.250000  22.00000   90.00000
max    100.000000  23.00000  100.00000

In [18]:
df_accurate["city"].unique()

<StringArray>
['Lahore', 'Karachi', 'Islamabad', 'Faisalabad', 'Rawalpindi']
Length: 5, dtype: str

In [19]:
df_accurate["city"].nunique()

5

In [20]:
df_accurate["city"].value_counts()

city
Lahore        18
Karachi       16
Islamabad     16
Faisalabad    16
Rawalpindi    14
Name: count, dtype: int64